version: '3'
services:
    rq-server-interview:
        container_name: rq-server-interview
        image: "redis:alpine"
        ports:
        - "6379:6379"
        environment:
        - REDIS_REPLICATION_MODE=master      

    api-interview:
        build: ./api
        command: sh run.sh
        image: master-image
        volumes:
            - ./api/:/app/
        expose:
            - 5000
        env_file:
            - ./.env
        depends_on:
            - db

    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=not_a_user
            - POSTGRES_PASSWORD=not_a_password
            - POSTGRES_DB=interview


    # WORKERS
    worker:
        image: master-image
        env_file:
            - ./.env
        depends_on:
            - rq-server-interview
        command: python3 worker.py

    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - api-interview

volumes:
    postgres_data:
